heartbeat8.heartbeat_stream_entity.*:
  type: config_entity
  label: 'Heartbeat stream entity config'
  mapping:
    hid:
      type: serial
      label: 'hid'
    message_id:
      type: string
      label: 'message_id'
    description:
      type: string
      label: 'description'
    message:
      type: string
      label: 'message'
    message_concat:
      type: string
      label: 'message_concat'
    perms:
      type: integer
      label: 'perms'
    group_type:
      type: string
      label: 'group_type'
