heartbeat8.heartbeat_stream_entity.*:
  type: config_entity
  label: 'Heartbeat stream entity config'
  mapping:
    hid:
      type: serial
      label: 'hid'
    message_id:
      type: string
      label: 'message_id'
    description:
      type: string
      label: 'description'
    message:
      type: string
      label: 'message'
    message_concat:
      type: string
      label: 'message_concat'
    perms:
      type: integer
      label: 'perms'
    group_type:
      type: string
      label: 'group_type'





#   // CTools export definitions.
#    'export' => array(
#      'key' => 'message_id',
#      'key name' => 'Message ID',
#      'primary key' => 'message_id',
#      'bulk export' => TRUE,
#      'identifier' => 'heartbeatmessagetemplate',
#      'object' => 'HeartbeatMessageTemplate',
#      'default hook' => 'heartbeat_template_info',
#      'list callback' => 'heartbeat_templates_names',
#      'delete callback' => 'heartbeat_message_template_delete',
#      //'export callback' => 'heartbeat_message_template_export',
#      'can disable' => TRUE,
#      'api' => array(
#        'owner' => 'heartbeat',
#        'api' => 'heartbeat',
#        'minimum_version' => 1,
#        'current_version' => 1,
#      ),
#    ),

node.type.*:
  type: config_entity
  label: 'Content type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    preview_mode:
      type: integer
      label: 'Preview before submitting'
    display_submitted:
      type: boolean
      label: 'Display setting for author and date Submitted by post information'
